import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import SmoothScroll from "@/components/SmoothScroll";

const lato = Lato({
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "L'Irresistible Alliance du Beignet",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/LogoIcon32.png", sizes: "32x32", type: "image/png" },
      { url: "/LogoIcon16.png", sizes: "16x16", type: "image/png" },
    ],
    apple: "/LogoIcon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${lato.className} min-h-full flex flex-col`}>
        <SmoothScroll />
        {children}
      </body>
    </html>
  );
}